### ISSUE TITLE
Doesn't seem to work with Unity 2020.1.17f1 and URP template?

### ISSUE THREAD

**Issue by ROBYER1** [sno/unity-webgl-responsive#3]
Hey, this looks fab, wanted to try it in a project using URP and was finding the build would just have a white screen, reproduced it again with a new URP template project in Unity 2020.1.17f1

In the developer tools in Chrome I see the error:
(index):36 Uncaught ReferenceError: UnityLoader is not defined
    at (index):36

Screenshot:
![image](https://user-images.githubusercontent.com/10745594/110376136-be164d80-804a-11eb-8488-e92dbbfeeab0.png)

**Comment by sno** [comment]
Thanks for the report! This is likely due to more recent versions of Unity using a different export / structure for the embed. I'm pretty busy these days but I'll have a look at this as soon as possible.
